### ISSUE TITLE
Strange TS error - using denodb

### ISSUE THREAD

**Issue by netanelmaroof** [deno-postgres/deno-postgres#165]
error: TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.conn;
           ~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:612:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufReader;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:613:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufWriter;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:614:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.packetWriter;
           ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:615:12

**Comment by KyleJune** [comment]
This module hasn't been updated yet for [Deno 1.3.2](https://github.com/denoland/deno/releases/tag/v1.3.2). Those errors are caused by changes in the newest version of TypeScript. You can either downgrade your Deno version and wait for this module to get updated or fork this repository to resolve those issues yourself. If you decide to fork and resolve the issues I'd recommend creating a PR.
